### ISSUE TITLE
Terraform v0.15.0 removed "map" and "list" functions

### ISSUE THREAD

**Issue by dvdlevanon** [Guimove/terraform-aws-bastion#106]
While it already fixed by:
https://github.com/Guimove/terraform-aws-bastion/pull/105/files

A new version isn't publish yet.

This works:
```
module "bastion" {
  source                             = "github.com/Guimove/terraform-aws-bastion"
}
```

This doesn't work:
```
module "bastion" {
  "source" = "Guimove/bastion/aws"
}
```

Any plan to release soon?

**Comment by Guimove** [comment]
Version v2.3.0 as been released, sorry for the delay

**Comment by dvdlevanon** [comment]
Thank you @Guimove
