### ISSUE TITLE
CloudWatch Alarms?

### ISSUE THREAD

**Issue by jnewton03** [Guimove/terraform-aws-bastion#110]
Hello,
I am trying to figure out how I can add CloudWatch Alarms for my bastion host(s) but I do not see an output in the module that I can feed to the CloudWatch Alarm Terraform code.  Would it be possible to add this functionality or provide a workaround?  

Additionally it would be nice to include an option for cloudwatch alarms that will trigger an autoscaling event of the bastion host ASG.  

Thanks!

**Comment by henadzit** [comment]
Hi @jnewton03, I created [a PR that adds the autoscaling group name to outputs](https://github.com/Guimove/terraform-aws-bastion/pull/112). This should allow configuring alarms on top of this module like this:

```
resource "aws_cloudwatch_metric_alarm" "your-alarm" {
  alarm_name          = "your-alarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "2"
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = "120"
  statistic           = "Average"
  threshold           = "80"

  dimensions = {
    AutoScalingGroupName = module.bastion.bastion_auto_scaling_group_name
  }
}
```

**Comment by jnewton03** [comment]
Hi @henadzit !  This is great!  Thank you!
