### ISSUE TITLE
How to copy the private key to bastion host?

### ISSUE THREAD

**Issue by xiaoronglv** [Guimove/terraform-aws-bastion#111]
This module is awesome, it helps me to set up different Linux users in the bastion host and track the activity of each session.

The following is an typical workflow of bastion host.

```
developer ====== key1 ====> bastion host ======  key2 =====> web server
```

1. the developer uses the private key of key1 to ssh login bastion host.

2. Then, the developer uses key2 to log in the webserver.

For step1, all I need to do is drop the public key to s3. But for step2, is there a convenient way to sync the private key to the bastion host?

So each developer don't have to copy the private key to the bastion host folder `~/.ssh`

**Comment by xiaoronglv** [comment]
should I use `SSH Agent forwarding` rather than another key-pair to login production web server?

https://www.reddit.com/r/sysadmin/comments/9z3xgg/ssh_bastion_server_private_key_storage_and/

**Comment by xiaoronglv** [comment]
update: `SSH Agent forwarding` seems it doesn't work. Here is the error msg.

```
> ssh -A ryan@xxx.com ec2-user@10.2.1.68                                                                                   
This bastion supports interactive sessions only. Do not supply a command
```

**Comment by xiaoronglv** [comment]
update: `SSH Agent forwarding` works!

![2021-07-09_21-58-16](https://user-images.githubusercontent.com/1224077/125089277-d84b5f80-e100-11eb-8f5a-ef6ef4b419c1.jpg)

**Comment by Guimove** [comment]
Hello @xiaoronglv 
Sorry I was on holiday, finally where you able to make it work ? 

In a previous use case, secret keys were generated by a lambda, that generate and sync the key for all production servers and store them on secret manager.
Then on the bastion, I made a wrapper to the SSH binary,  to download the key from the secret manager every time I need to connect to a server.
This allows me to rotate the key every day for security purpose (requested by security team).
