### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by henadzit** [Guimove/terraform-aws-bastion#116]
Hello, sorry for bothering you again. Could you please create a new tag with the latest merged PR https://github.com/Guimove/terraform-aws-bastion/pull/115, so it's available via terraform registry? Thank you in advance!

**Comment by Ashtonian** [comment]
@Guimove - can you fix, I think the versions are broken, looks like there were two commits to 2.2.x which never made it to 2.3 ?

**Comment by Guimove** [comment]
Yep sorry, I fixed all issues in v2.3.1

**Comment by Ashtonian** [comment]
Thank you!
