### ISSUE TITLE
unable to access private instances from bastion host

### ISSUE THREAD

**Issue by jwhitcraft** [Guimove/terraform-aws-bastion#12]
By default, there is now way to allow the bastion host to have access the instances running in my private subnets, the way i've worked around this is to add an egress rule for port 22 to my private subnet cidrs.

If there is another way to get around this, it would be helpful to know and document.

Thanks.

**Comment by Guimove** [comment]
Hello,

You need to attach you private instances to the "private_instances_security_group"

It allow ssh connection from instances on the "bastion_host_security_group"
