### ISSUE TITLE
Issue when specifying bastion_security_group_id

### ISSUE THREAD

**Issue by xposix** [Guimove/terraform-aws-bastion#121]
Hello,

First of all congratulations for the excellent work. It took me a while to find a template for a bastion host that would come with all the features I needed.

I'm creating a SG separately due to firewall policies. So I'm passing the ID of that SG to this module using
```
bastion_security_group_id   = aws_security_group.bastion.id
```

But I always get this issue: 

```
│ Error: Invalid count argument
│
│   on .terraform/modules/ec2-bastion-server/main.tf line 71, in resource "aws_security_group" "bastion_host_security_group":
│   71:   count       = var.bastion_security_group_id == "" ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created.
│ To work around this, use the -target argument to first apply only the resources that the count depends on.
╵
make: *** [apply] Error 1
```

I'm using Terraform 1.0.11. This issue doesn't happen when creating the bastion without specifying the `bastion_security_group_id` first, and then updating.

**Comment by Guimove** [comment]
This should be fix now
