### ISSUE TITLE
Override name tag on autoscaling group

### ISSUE THREAD

**Issue by bee-keeper** [Guimove/terraform-aws-bastion#125]
Hi there,

Thanks for your work on this module.

I'm curious why 'Name' tag is defined [here](https://github.com/Guimove/terraform-aws-bastion/blob/master/main.tf#L325) on the auto scaling group resource.  With this logic in place it's not possible to override this tag as it is elsewhere due to use of `merge` over `concat`.  

Would you accept a PR to merge the ASG tags in a way that allows for overriding `Name`?

**Comment by Guimove** [comment]
Hello,

Yes feel free to propose something and I'll review it.

Thanks,
