### ISSUE TITLE
attach existing security group id

### ISSUE THREAD

**Issue by maximbaran** [Guimove/terraform-aws-bastion#138]
I am trying to add custom security group
`bastion_security_group_id = module.custom-networking.bastion_sg_id`

**bastion_sg_id** configured as output (string) from custom module (aws_security_group resource): 

```
output "bastion_sg_id" {
  value   = aws_security_group.baran-bastion-sg.id
}
```

but received error: 

```
│ Error: Invalid count argument
│
│   on .terraform\modules\bastion\main.tf line 23, in resource "aws_security_group" "bastion_host_security_group":
│   23:   count       = var.bastion_security_group_id == "" ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only   
│ the resources that the count depends on.
```

This issue doesn't happen when creating the bastion without specifying the bastion_security_group_id first, and then updating.

**Comment by Guimove** [comment]
Hi there

We have made updates to the module to address this issue. We recommend trying the latest version of the module, as it includes improvements and bug fixes. By using the latest version, you should be able to specify the `bastion_security_group_id` without encountering the "Invalid count argument" error.

If you still experience any difficulties or have further questions, please let us know. We are here to assist you.
