### ISSUE TITLE
Unable To Set "Instance Metadata Service Version 2"

### ISSUE THREAD

**Issue by Tohmua** [Guimove/terraform-aws-bastion#146]
The EC2 instance is using version 1 of the Instance Metadata Service, which is prone to publicly known weaknesses.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance

Setting: `http_tokens` to `required` as part of the `launch_template` can solve this.

**Comment by Guimove** [comment]
Fixed in #147
