### ISSUE TITLE
Issue when loging "Cannot open /var/log/bastiont..."

### ISSUE THREAD

**Issue by Miguel-KD** [Guimove/terraform-aws-bastion#151]
Hi, first of all, thank you for your module is pretty useful. For some months I found some of the users sometimes have a problem accessing the bastion with this error "script: cannot open /var/log/bastion/2023-02-06_12-19-59_AWESOMEUSER_D66uDuD5C6OT2AUVBou42SRsyRa0tDmm.data: Permission denied" . 
It happened to me with multiple people and different environments, usually, I just solve it by destroying and creating the whole bastion (commenting on the module) and applying it. Recreate again probably is not the best option. 

Can I help you to identify the problem even coding some lines to help? Where should I be checking? 

Thanks

**Comment by jirkabs** [comment]
Duplicate of #127.

**Comment by Miguel-KD** [comment]
Thanks @jirkabs
