### ISSUE TITLE
SSH Host-Key Pinning?

### ISSUE THREAD

**Issue by hotzen** [Guimove/terraform-aws-bastion#153]
Hello,
we currently use the `extra_user_data_content` to specify a shell script that fetches host-keys from AWS secrets-manager to store them and effectively pin the ssh host key to avoid regeneration after AMI updates:

```
get_secret_string ${secret_arn_ed25519} | jq ".public" -r > /etc/ssh/ssh_host_ed25519_key.pub
get_secret_string ${secret_arn_ed25519} | jq ".private" -r > /etc/ssh/ssh_host_ed25519_key

get_secret_string ${secret_arn_ecdsa} | jq ".public" -r > /etc/ssh/ssh_host_ecdsa_key.pub
get_secret_string ${secret_arn_ecdsa} | jq ".private" -r > /etc/ssh/ssh_host_ecdsa_key
```

this does not work properly though, it seems we're missing the rsa key, a `ssh-keyscan bastion` does only respond with a changing `ssh-rsa` key after AMI updates.

Could you advise where to put keys of which algo and does it make sense to make ssh-host-key-pinning an actual first class feature of the bastion?

Thanks for the great work, Kai

**Comment by hotzen** [comment]
double checked `systemctl status sshd`  which yields
```
Mar 15 09:51:00 ip-10-117-5-254.eu-central-1.compute.internal sshd[4699]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
```

so that's  on us...

**Comment by jtownsend-amp** [comment]
@hotzen can you please share the rest of your user data content script? I am looking to implement a similar solution.
