### ISSUE TITLE
Bug - Incompatible with v5.0.0 of terraform-aws-modules/vpc/aws

### ISSUE THREAD

**Issue by harelguy** [Guimove/terraform-aws-bastion#163]
When running on Terraform cloud:
```
Initializing Terraform Cloud...
Initializing modules...
Downloading registry.terraform.io/Guimove/bastion/aws 3.0.4 for bastion...
- bastion in .terraform/modules/bastion
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 5.0.0 for vpc...
- vpc in .terraform/modules/vpc

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.0, >= 5.0.0"...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: no available releases match the given constraints ~> 4.0, >=
│ 5.0.0
```

This is due to a recent (May 30, 2023) upgrade of Terraform's AWS module for VPC v5.0.0 which introduced a dependency on hashicorp/aws >= 5.0.0 whereas the bastion module is locked to ~> 4.0

**Comment by Guimove** [comment]
Thank you for reporting the bug and for using the module. I appreciate your effort in providing feedback.

The issue you reported should be resolved with commit hash 3de458b4133c60ca6b3b780aca2ff6999e9cf216. I have incorporated this fix in version 3.0.6 of the module.

Please give version 3.0.6 a try and verify if the issue has been successfully resolved. Your feedback is valuable to me and it helps me improve the module.

Once again, thank you for your support and for helping me enhance the quality of the module.

**Comment by harelguy** [comment]
Thank you @Guimove for this module, it is very helpful!

**Comment by harelguy** [comment]
I have tested the module version 3.0.6, the module correctly installs. There is another problem with the security group but I'm not sure it's related, so will open a new issue.
Thanks again!
