### ISSUE TITLE
Changing the bucket name should force an update to the sync script

### ISSUE THREAD

**Issue by aequasi** [Guimove/terraform-aws-bastion#28]
If you change the bucket name, the sync script continues to check the old bucket name

**Comment by Guimove** [comment]
Could you please details how to reproduce ? 

You deployed a first time with bucket_name = bucketA? 
The you changed the bucket_name to bucketB and redeploy? 
After this second deploy the user_data is not updated?

**Comment by aequasi** [comment]
well, just changing the bucket name doesn't force a re-deploy when you `apply`, so when you check in the script that syncs the keys, it still references the old bucket name
