### ISSUE TITLE
1.1.0 Does Not Work - Wrong AMI Architecture

### ISSUE THREAD

**Issue by jedibatman** [Guimove/terraform-aws-bastion#36]
There appears to have been a PR #35 that was merged in, but no new release was created that actually allows the use of this module in the terraform registry.

I know this because I am currently trying to use this module and am getting an obscure error in the activity log of the ASG. This error led me to do some investigation and the AMI that was selected for the launch configuration is arm64 architecture -- which is not compatible with an instance type of `t2.nano`.

I believe all that needs to be done is to create a new GitHub release that includes the recently merged changes to resolve this, unless I am misunderstanding.

**Comment by Guimove** [comment]
You were right, I forget to create the new release.
The change is now available on the release v1.1.1
