### ISSUE TITLE
Unable to use `aws` CLI when behind proxy

### ISSUE THREAD

**Issue by Wykiki** [Guimove/terraform-aws-bastion#72]
Hello,

The `aws` CLI is unable to request S3 API when behind a HTTP Proxy.

Things I needed to do manually inside the EC2 instance to allow `aws` CLI was to declare `*_proxy` env variables :
- `http_proxy` : `http://my-proxy:3128/`
- `https_proxy` : `http://my-proxy:3128/`
- `no_proxy` : `localhost,127.0.0.1,169.254.169.254`

Is there a way to provide those environment variables via the Terraform module ?

Thanks for your answer !

**Comment by Guimove** [comment]
Hello,

You can use `extra_user_data_content` to add these variables to the system environnement.

**Comment by Wykiki** [comment]
Oh yeah I missed that variable, thanks for the tips !
