### ISSUE TITLE
SSH ingress rule

### ISSUE THREAD

**Issue by robcxyz** [Guimove/terraform-aws-bastion#81]
Hope I'm not being thick here, but is this rule needed?

https://github.com/Guimove/terraform-aws-bastion/blob/master/main.tf#L85

Seems like you wouldn't want an ingress rule to your bastion from private subnets.  Just ingress from public (corp IP or something) and then ingress rules on your private sgs.  Or do I have this wrong?

Thanks for the work.

**Comment by Guimove** [comment]
Hello,

I agree with you that linking sg to sg is really more secure, but many people asked this, but is personally I use the sg to sg old version.

I should find time to add the two solution with a switch to chose between them.
