### ISSUE TITLE
[BUG] Parameter `public_ssh_port` not used in `sshd_config`

### ISSUE THREAD

**Issue by Wykiki** [Guimove/terraform-aws-bastion#86]
Hello,

I tried to set some exotic ports as follow :

```
public_ssh_port = 22022
private_ssh_port = 22
```

But then I cannot access the bastion.

It looks like it is not taken into account in the `sshd_config` file update from the `user-data.sh` : https://github.com/Guimove/terraform-aws-bastion/blob/master/user_data.sh#L21

Not sure if this is the cause.

Thanks !

**Comment by Guimove** [comment]
Hello
Should be resolved by #88
