### ISSUE TITLE
Allow setting non-standard ssh port

### ISSUE THREAD

**Issue by jwhitcraft** [Guimove/terraform-aws-bastion#9]
To add extra security to to the bastion host, it would be nice to be able to set the port that the LB uses to forward the to the ssh port,  currently it's locked at 22, but according to my company's security policy, we can not have port 22 as the open port, we have to use a non-standard port.

Thanks.

**Comment by Guimove** [comment]
I'll add two parameters : 

- public_ssh_ port = the port to use from your computer to the bastion
- private_ssh_port = the port between bastion and private instance
