### ISSUE TITLE
Add depends_on s3 bucket to ASG resource

### ISSUE THREAD

**Issue by jnewton03** [Guimove/terraform-aws-bastion#94]
In my instance I had given an S3 bucket name that was not available.  However, the ASG still got created even though the S3 bucket did not, so the user data script that ran never created /logs and any keys dropped in /public-keys didn't work.  

I would suggest adding a depends_on to the ASG such that the ASG will only be created IF the s3 bucket is successfully created.  Let me know if you want a PR for this.

**Comment by Guimove** [comment]
I've made this change, thanks you.
