### ISSUE TITLE
bucket ACL breaks with provider 3.15

### ISSUE THREAD

**Issue by Next-gerardovazquezrodriguez** [Guimove/terraform-aws-bastion#98]
According https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html in S3 acl    = "bucket-owner-full-control" is ignored, it also breaks with provider 3.15

**Comment by terrancej** [comment]
bump

**Comment by Guimove** [comment]
Hello,

Did you try to update the version of the module ? This was fixed since the 15th of November

**Comment by Guimove** [comment]
try with v2.2.1

**Comment by Next-gerardovazquezrodriguez** [comment]
Thanks! will try that version :)
